# Settings Configuration File for TMC Zombie Survival (TMCZ) plugin
#
# IMPORTANT!!!  -- THE TMCz ITEM FORMAT HAS CHANGED!!!!! --
#
#  ITEM_NAME|QUANTITY|DAMAGE|POTION_NAME|EXTENDED|UPGRADED|LORE_TEXT|DISPLAY_NAME|PLAYER_NAME|ENCHANTMENTS
#
#  Item Name   : The Internal name of the item. REQUIRED (Consult Minecraft wiki for Item names)
#  Quantity    : The Quantity of the Item. REQUIRED (Always required, but ignored where noted below)
#  Damage      : The Damage Value of tha item. Optional. If item can take damage, this is the damage value of the item
#                 0 = New item, no damage
#
#  The following properties are OPTIONAL, however, if one is specified, then all previous values must be specified
#     even if the value is blank. For example, the damage value of a POTION can be anything as it is ignored.
#     Another Example: If LORE text is specified, and the item is NOT a potion, the potion values must be present
#     and empty
#
#  POTION_NAME : If Item Name is POTION, SPLASH_POTION, or LINGERING_POTION, this is the name of the potion effect
#  EXTENDED    : Boolean property (true or false) is the potion an extended version
#  UPGRADED    : Boolean property (true or false) is the potion an upgraded version (e.g: Luck II)
#  LORE_TEXT   : Text string of the Lore property of the item. Displayed on the tool text in game
#  DISPLAY_NAME: Display name of item in game (as if renamed on an anvil)
#  PLAYER_NAME : Only works on player skull - The username of the player whose skull it is.
#  ENCHANTMENTS: a list of enchantments and the level to apply to the item. Enchantment must be of a valid value and
#                 valid enchantment for the item. Invalid levels will be automatically set to a valid level, and
#                 invalid enchantments for the item will not be applied.
#
# EXAMPLE:   AIR|0|0
#                Default item: Stack of AIR blocks with 0 quantity and 0 damage
# EXAMPLE:   POTION|1|0|LUCK|FALSE|FALSE|Not so lucky, eh|Luck -1
#                Regular LUCK I potion. with Lore Text "Not so lucky, eh" and display name "Luck -1"

# These two options are (TODO): not yet implemented

debug: true              # If true: some hidden debug features are available for developers.
check-for-updates: true  # If true: Plugin will check for updates to the required TMC-LIB.

# This section defines the world where TMCz Zombie Survival will be played out.

world:
  name: world                # Internal world name of authorized world. Must be specified for certain features to work
  single: true               # If false: dependant modules are active on all server worlds
  op-is-god: true            # If true: any OP player will not take damage caused by modules below
  record-zombie-death: true  # If true: Plugin will track all zombie kills across specified world.

########################################################################################################################
#####   INCLUDED MODULES - Enable each individually for customized servers                                         #####
########################################################################################################################

# The autosave system, when enabled, will continually save the current game state of all players to disk, and when the
# server starts up will load the saved states into memory so that when players reconnect, they'll start when and where
# they were.
# TODO: NOT IMPLEMENTED YET

autosave-system:      # This module runs for all players on the server. Single World Configuration is ignored.
  enabled: false      # If true: all tmcz players data is backed up to disk on a set interval
  minutes: 5          # Approximate number of minutes between save intervals, laggy server will have longer intervals

#-----------------------------------------------------------------------------------------------------------------------

# The Bleed System introduces gameplay where getting hurt by different types of damage causes you to bleed. Bleeding
# can be stopped by applying a bandage. The player can bleed out and die if the bleeding is not stopped before they
# lose all of their hearts. See below for configuration options.
# TODO: Feature complete

bleed-system:
  enabled: false         # If true: player bleeding system is activated
  only-in-game: false    # If true: Bleed system only works for players who are playing TMCz
  server-wide: false     # If true: Bleed System affects all worlds on server, only-in-game property ignored.
  particles: 3           # Number of blood particles to display per damage hit
  chance: 5              # Percent chance that a valid hit will cause bleeding
  damage: 1              # How many health levels are taken each bleed hit (half hearts)
  ticks: 200             # Number of ticks between damage hits when bleeding
  healer-item: PAPER     # Item that healer uses to stop the bleeding (currently only supports items in minecraft:)

#-----------------------------------------------------------------------------------------------------------------------

# This is the core of TMCz (MineZ Clone). The settings in this module regulate nearly every aspect of the actual game.
# The other systems add other aspects of the game, but this control the rules. When this plugin is paired with a
# specifically curated map, this can create a very enjoyable game play experience.
# TODO: NOT IMPLEMENTED YET

game-system:               ## The core TMCz Game Mechanics
  enabled: false           # If true, the TMCz game play is enabled on the specified world
  return-to-spawn: true    # If true: players on game world who don't have a save file are sent back to world spawn.
  pvp: true                # If true: players in game on game world can damage each other
  bandit-tag: true         # If true: players who kill other players above limit set are flagged as a bandit
  bandit_kills: 5          # The number of other player kills a player needs to be flagged as a bandit
  bandit-lose-tag: true    # If true: a bandit can lost their bandit tag if they heal other players
  bandit-healer: 15        # The number of other player heals a bandit must make to lose their bandit tag
  healer-tag: true         # If true: a player who heals other players can be flagged as a healer
  healer-heals: 10         # The number of other player heals a player must make to earn the healer tag
  sugar-speed:
    enabled: true          # If true: eating sugar (right click with sugar) will give player a speed potion effect
    duration: 10           # Seconds for speed potion effect to last
    multiplier: 1          # Speed potion effect level to give (1 = Speed I, 10 = Speed X, etc)
  start-kit:
    enabled: true          # If true: player's inventory is cleared and they are given these items when game is started
    helmet:   leather_helmet|1|-1|41     # When someone enters the game, these armor items will be added to the player.
    armor:    leather_chestplate|1|-1|64 # If you do not want the player to be armed, simply remove the line and the
    leggings: leather_leggings|1|-1|58   # armor will not be enabled.
    boots:    leather_boots|1|-1|57
    items:                 # Items player is given when spawned into the game. each item is in TMCz Item Format
      - wooden_sword|1
      - potion|1|-1|0      # These items are demo items and should not be considered the production spawn kit items
      - bread|1
  spawn:
    teleport: true         # If true: the player is teleported to a new location when they start the game
    random: true           # If true: will choose a random location within area bound by zone1 and zone2
    zone1: -100|-100       # One corner of the bounding box for random spawns in <x>|<z> format
    zone2: 100|100         # Other corner of the bounding box for random spawns in <x>|<z> format
    static-locations:      # List of static mobs locations. Can be set in game with command /tmcz addspawn

#-----------------------------------------------------------------------------------------------------------------------

# The health system controls how many hearts of health a player has. By default, the player has 20 points of health, or
# 10 hearts. However, that can be modified here. You can configure your server to limit the number of hearts a player
# can have.
# TODO: NOT IMPLEMENTED YET

health-system:
  enabled: false       # If true: Health System is active
  only-in-game: false  # If true: Health system only works for players who are playing TMCz
  server-wide: false   # If true: Health System affects all worlds on server, only-in-game property ignored.
  start: 10            # Health level player is set to when they respawn, 1 heart = 2 points
  maximum: 10          # Maximum health level the player can have. Setting lower than 20 makes the game harder
  regen: false         # If true: Player's health regenerates normally when satiated
  food-gives: true     # If true: Eating food will restore health

#-----------------------------------------------------------------------------------------------------------------------

# The infection system introduces gameplay mechanic where damage from a zombie has a chance to infect the player. An
# infected player will take damage as the infection spreads until it leads to death. The player or another player
# can administer antibiotics which will cure the infection. However, the longer the player has been infected, the more
# antibiotic will need to be applied to kill the infection.
# TODO: NOT IMPLEMENTED YET

infection-system:
  enabled: false         # If true, Infection system is activated
  only-in-game: false    # If true: Infection system only works for players who are playing TMCz
  server-wide: false     # If true: Infection System affects all worlds on server, only-in-game property ignored.
  duration: 15           # Seconds of Confusion effect per damage hit
  chance: 5              # Percent chance that zombie hit will cause infection
  damage: 5              # Number of health points are taken each damage hit
  ticks: 600             # Number of ticks between damage hits
  check-ticks: 35        # Number of ticks after start drinking milk to check if finished.
  hurl: true             # If true: Player's food bar will deplete each damage hit
  healer-item: dyes|1|10 # Item that healer uses to cure infection in TMCz item format. (qty ignored)

#-----------------------------------------------------------------------------------------------------------------------

# PLEASE NOTE: If this system is enabled, all block breaking and placing will be prohibited on the world configured
# at the top of this configuration file, as if WorldGuard were enabled. Only players with the tmcz.builder permission
# and Server Operators will have the ability to build and break freely. All other block interactions will be tracked
# according to the following configurations
# TODO: Feature Complete

item-system:
  enabled: true           # If true: the following custom item interactions are enabled
  end-grenade:
    enabled: true         # If true: ender pearls will function as grenades
    only-in-game: true    # If true: end-grenades only work for players playing TMCz
    server-wide: false    # If true: end-grenades work on all server worlds, only-in-game property ignored.
    protect-world: true   # If true: all explosions won't destroy world blocks
    radius: 3             # the radius of the explosion of ender grenade. Don't set too high
  melon:
    enabled: true         # If true: players can harvest melons for melon slices/food
    only-in-game: true    # If true: players can only harvest melons while playing TMCz
    server-wide: false    # If true: any player on the server can harvest melons, only-in-game property ignored.
    tool: wooden_hoe      # internal item name the tool that can break melons
  mushroom:
    enabled: true         # If true: players can harvest mushrooms for food
    only-in-game: true    # If true: players can only harvest mushrooms while playing TMCz
    server-wide: false    # If true: any player on the server can harvest mushrooms, only-in-game property ignored.
    tool: iron_shovel     # Internal item name of the tool that can harvest mushrooms
    respawn: true         # if True, broken mushrooms respawn after a specified number of seconds
    respawn-seconds: 300  # number of seconds before a mushroom will respawn in its original location
  cobweb:
    enabled: true         # If true: players can break map cobwebs
    only-in-game: true    # If true: players can only break cobwebs while playing TMCz
    server-wide: false    # If true: any player on the server can break cobwebs this way, only-in-game property ignored.
    tool: wooden_hoe      # Internal item name of the tool that can break cobwebs
    drop: true            # If true: broken cobwebs drop a place-able cobweb item
    respawn: true         # If true: broken cobwebs will re-spawn in their original location
    respawn-seconds: 300  # number of seconds before a cobweb will re-spawn after it is broken
  block-protection:
    place: true           # If true: players can place specified blocks, all other block placing is prohibited
    break: true           # If true: players can break specified blocks, all other block breaking is prohibited
    op-can-build: true    # If true: OPs are exempt from block/item protection and items placed are not tracked
    only-in-game: false   # If true: block protection is only enforced against players who are playing TMCz
    server-wide: false    # If true: block place protection is enforced server-wide. Ignores previous setting
    allowed-items:        # list of items allowed to be placed in <itemName>|<Despawn Seconds>|<Respawn Seconds> format
      - torch|300|-1
      - melon_block|60|-1
      - stone_button|60|60
      - lever|60|60
      - web|500|-1

    # NOTES:  1. To allow certain placed blocks to not despawn, set the despawn seconds value to -1
    #         2. To allow certain broken blocks to not respawn, set the respawn seconds value to -1
    #         3. To allow placing of certain block types, but not breaking, set the respawn seconds to 0
    #         4. To allow breaking of certain block types, but not placing, set the despawn seconds to 0
    #         5. Player placed blocks will not respawn, regardless of respawn setting
#-----------------------------------------------------------------------------------------------------------------------

# Stack limits are only able to be applied SERVER WIDE! If you run a server with multiple worlds and the Zombie world
# is only one of many worlds on your server, stack limits will apply to your Zombie Survival worlds as well. If you
# want to enabled stack limits only in the Zombie Survival game, you'll have to setup a dedicated server for TMCz and
# setup cross-server portals to transport your players back and forth. (This is how the lobby of the ShotBow Network works.)
# TODO: Not Implemented Yet

limit-stacks:
  enabled: false

#-----------------------------------------------------------------------------------------------------------------------

# The Thirst System introduces gameplay where the player will continually get thirsty and will have to drink water in
# order to stay hydrated. The Level number is the player's Hydration number. When it hits zero, the player begins
# to take thirst damage, which can lead to death.
# TODO: Feature Complete

thirst-system:
  enabled: false       # If true: Player thirst system will be activated
  only-in-game: true   # If true: Thirst system only works for players who are playing TMCz
  server-wide: false   # If true: Thirst System affects all worlds on server, only-in-game property ignored.
  thirst-ticks: 420    # Number of ticks between losing one thirst level
  damage-ticks: 60     # When thirst is at 0, number of ticks between damage hits
  damage-hit: 1        # Amount of health each damage hit takes
  full: 20             # How many levels equals a fully quenched player
  refill-water: 9      # How many levels drinking water will restore
  refill-potion: 5     # How many levels drinking a potion will restore
  break-chance: 20     # Percent chance that the water bottle will break
  start: 10            # Player's thirst level when they spawn into the game
  parch-1: 10          # What level will message thirst.parch-1 display to player
  parch-2: 7           # What level will message thirst.parch-2 display to player
  parch-3: 3           # What level will message thirst.parch-3 display to player
  parch-4: 1           # What level will message thirst.parch-4 display to player

#-----------------------------------------------------------------------------------------------------------------------

# The visibility system enhances the built-in visibility system within Minecraft. Crouching by default will cause the
# player to be less noticeable to mobs. This visibility system uses the experience bar to visually display how loud
# the player is in their environment, and the quieter the player is, the less they'll be noticed by mobs.
# TODO: Feature Complete

visibility-system:
  enabled: false       # If true: Visibility system will be activated (currently display only)
  only-in-game: true   # If true: Visibility system only works for players who are playing TMCz
  server-wide: false   # If true: Visibility System affects all worlds on server, only-in-game property ignored.
  ticks: 10            # Number of ticks between updating your visibility bar

#-----------------------------------------------------------------------------------------------------------------------

# The mob-controls section modifies certain characteristics of existing vanilla mobs, specifically zombies since this
# is a Zombie Survival game. These configurations are currently server-wide.
# TODO: Zombie Complete
# TODO: Suppress other mobs not complete yet

mob-controls:
  zombie:                   # Special controls for Zombies, since this is a zombie survival game
    enabled: true           # if true: following zombie configs are activated
    can-burn: false         # If true: Zombies will burn in the daylight.
    head-hides: true        # if true: Zombies will randomly drop a zombie head, wearing head hides you from targeting
    head-drop-chance: 1000  # 1-out-of-x chance that a zombie will drop a head.
    head-break-chance: 20   # 1-out-of-x chance that a worn zombie head will break when player takes damage

#-----------------------------------------------------------------------------------------------------------------------
